pdgssvx: fix call to dist_psymbtonum when fact is SamePattern_SameRowPerm
In cases where parallel symbolic factorisation with reusing the row
and column permutations (i.e., Fact is SamePattern_SameRowPerm), the
function ddist_psymbtonum() is incorrectly called and SuperLU_dist
exits with the following error message:

  ERROR: call of dist_psymbtonum with fact equals SamePattern_SameRowPerm.

This is already noted in the comments to ddist_psymbtonum():

  "This routine should not be called for this case, an error is
  generated.  Instead, pddistribute routine should be called."

A valid fix seems to be to uncomment a line in the calling function,
pdgssvx(), which handles the case when Fact is equal to
SamePattern_SameRowPerm by instead calling pddistribute(), as
suggested in the above-mentioned comment.

The error can be easily reproduced with the following command:

  mpirun -np 2 pddrive3 -r 1 -c 2 -p 0 -q 5 -s 1 EXAMPLE/big.rua